version: '3'

services:
    frost:
        image: fraunhoferiosb/frost-server:1.9
#        build:
#            context: ./FROST-Server
#            dockerfile: Dockerfile_web
#            args:
#               GITHASH: v1.9
        environment:
          - serviceRootUrl=${FROST_SELF_URL}
          - persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.postgres.stringid.PostgresPersistenceManagerString
          - persistence_idGenerationMode=ServerAndClientGenerated
          - persistence_db_driver=org.postgresql.Driver
          - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
          - persistence_db_username=sensorthings
          - persistence_db_password=ChangeMe
          - http_cors_enable=true 
          - defaultTop=1000
          - maxTop=2147483647
#          - useAbsoluteNavigationLinks=false
        restart: unless-stopped
        ports:
            - 8080:8080
            - 1883:1883
            - 9876:9876
        depends_on:
            - database

    database:
        build:
            context: ./Frost-Server
            dockerfile: Dockerfile_db
        restart: unless-stopped
        volumes:
            - database-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=sensorthings
            - POSTGRES_USER=sensorthings
            - POSTGRES_PASSWORD=ChangeMe

    bridge:
        build:
            context: ./java-mqtt-kafka-bridge
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - kafka
            - frost

    kafka:
       image: landoop/fast-data-dev 
       environment:
           - SAMPLEDATA=0
           - RUNTESTS=0
           - ADV_HOST=${FROST_HOST}
       ports:
           - 3030:3030
           - 2181:2181
           - 9092:9092
       volumes:
           - kafka-data:/data

#    openelevation:
#       build:
#            context: ./open-elevation
#            dockerfile: docker/Dockerfile
#       volumes:
#               - openelevation-data:/code/data
#
#    openelevation-init:
#       build:
#            context: ./open-elevation
#            dockerfile: docker/Dockerfile
#       volumes:
#               - openelevation-data:/code/data
#       command: ["/code/create-dataset.sh"]
#
    nginx:
       build: ./nginx
       ports:
         - 80:80
       environment:
         - NGINX_HOST=${FROST_HOST}
       depends_on:
         - frost
#        - openelevation
       

volumes: 
        database-data:
        kafka-data:
#        openelevation-data:
