version: '3'

services:
  frost:
    build:
        context: ./FROST-Server
        dockerfile: Dockerfile_web
        args:
          GITHASH: v1.8
    environment:
      - serviceRootUrl=http://localhost:8080/FROST-Server 
      - persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.postgres.stringid.PostgresPersistenceManagerString
      - persistence_idGenerationMode=ServerAndClientGenerated
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - database
      
  database:
    build:
      context: ./FROST-Server
      dockerfile: Dockerfile_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - ./FROST-Server/postgres_data/:/var/lib/postgresql/data

  bridge:
    build:
      context: ./java-mqtt-kafka-bridge
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - frost
