version: '3'

services:
    certbot-init:
               image: certbot/certbot
               ports: 
                - 80:80
               volumes:
                       - letsencrypt-conf:/etc/letsencrypt
               command: "certonly --standalone --preferred-challenges http --agree-tos --email riedel@teco.edu  -d $FROST_HOST"

volumes: 
        letsencrypt-conf:
