version: '3'

services:
    frost:
        image: fraunhoferiosb/frost-server:1.9
        environment:
          - serviceRootUrl=${FROST_SELF_URL}
          - persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.postgres.stringid.PostgresPersistenceManagerString
          - persistence_idGenerationMode=ServerAndClientGenerated
          - persistence_db_driver=org.postgresql.Driver
          - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
          - persistence_db_username=sensorthings
          - persistence_db_password=ChangeMe
          - http_cors_enable=true 
          - defaultTop=1000
          - maxTop=2147483647
        restart: unless-stopped
        ports:
            - 8080:8080
            - 1883:1883
            - 9876:9876
        depends_on:
            - database

    database:
        build:
            context: ./Frost-Server
            dockerfile: Dockerfile_db
        restart: unless-stopped
        volumes:
            - database-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=sensorthings
            - POSTGRES_USER=sensorthings
            - POSTGRES_PASSWORD=ChangeMe

    bridge:
        build:
            context: ./java-mqtt-kafka-bridge
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - kafka
            - frost

    kafka:
       image: landoop/fast-data-dev 
       environment:
           - SAMPLEDATA=0
           - RUNTESTS=0
           - ADV_HOST=${FROST_HOST}
       ports:
           - 3030:3030
           - 2181:2181
           - 9092:9092
       volumes:
           - kafka-data:/data

    nginx:
       build: 
            context: ./nginx
            dockerfile: Dockerfile
       ports:
         - 80:80
         - 443:443
       environment:
         - NGINX_HOST=${FROST_HOST}
       depends_on:
         - frost
         - certbot
       restart: unless-stopped
       volumes:
          - letsencrypt-conf:/etc/letsencrypt
          - letsencrypt-data:/var/www/certbot
       command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

    certbot:
               image: certbot/certbot
               restart: unless-stopped
               volumes:
                       - letsencrypt-conf:/etc/letsencrypt
                       - letsencrypt-data:/var/www/certbot
               entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes: 
        letsencrypt-data:
        letsencrypt-conf:
        database-data:
        kafka-data:
