#cloud-config
password: changeme!
ssh_authorized_keys: !include ~/.ssh/authorized_keys

apt:
  sources:
   docker:
     source: 'deb [arch=amd64] https://download.docker.com/linux/debian stretch stable'
     keyserver: https://keyserver.ubuntu.com
     keyid: 0EBFCD88
   ceph:
     source: 'deb https://download.ceph.com/debian-luminous/ stretch main'
     keyserver: https://keyserver.ubuntu.com
     keyid: E84AC2C0460F3994

package_upgrade: true

packages:
    - docker-ce
    - python3-pip
    - ceph-common
    - xfsprogs

mounts: 
    - [ '/dev/rbd0','/var/lib/docker','xfs','defaults,nofail,noatime,inode64,_netdev' ]

write_files:
        - path: /etc/ceph/rbdmap
          content: !include-raw $PWD/etc/ceph/rbdmap
        - path: /etc/ceph/ceph.client.smartaqnet.keyring
          content: !include-raw /etc/ceph/ceph.client.smartaqnet.keyring
        - path: /etc/ceph/ceph.conf
          content: !include-raw /etc/ceph/ceph.conf.template
        - path: /etc/cron.daily/ceph-snapshot
          content: !include-raw $PWD/etc/cron.daily/ceph-snapshot 
        - path: /etc/profile.d/ceph_default.sh
          content: !include-raw etc/profile.d/ceph_default.sh

#runcmd:
#  - [pip3, install, docker-compose]
